# Generated by Django 4.2.4 on 2023-09-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_img_proyecto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_proyecto',
            name='fecha_imagen',
            field=models.DateField(verbose_name='Fecha de la Imagen'),
        ),
        migrations.AlterField(
            model_name='img_proyecto',
            name='img_proyecto',
            field=models.ImageField(upload_to='proyectos', verbose_name='Imagen del proyecto'),
        ),
        migrations.AlterField(
            model_name='img_proyecto',
            name='is_active_img',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado Imagen'),
        ),
        migrations.AlterField(
            model_name='img_proyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto', verbose_name='Proyecto asociado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_proyecto',
            field=models.TextField(verbose_name='Descripción del Proyecto'),
        ),
    ]
