# Generated by Django 4.2.4 on 2023-09-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_banner', models.CharField(max_length=50, verbose_name='Titulo Banner')),
                ('fecha_banner', models.DateField()),
                ('foto_banner', models.ImageField(upload_to='banners')),
                ('is_active_video', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Cumpleagno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cumple', models.CharField(max_length=50, verbose_name='Titulo Cumpleaños')),
                ('fecha_cumple', models.DateField()),
                ('foto_cumple', models.ImageField(upload_to='cumpleaños')),
                ('is_active_video', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'db_table': 'cumpleagno',
            },
        ),
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_hit', models.CharField(max_length=50, verbose_name='Titulo Hito')),
                ('fecha_hito', models.DateField()),
                ('lugar_hito', models.CharField(max_length=50, verbose_name='Lugar')),
                ('is_active_hito', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'db_table': 'hito',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_Noticia', models.CharField(max_length=50, verbose_name='Titulo Noticia')),
                ('fecha_noticia', models.DateField()),
                ('img_noticia', models.ImageField(upload_to='noticias')),
                ('url_noticia', models.TextField()),
                ('is_active_noticia', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'db_table': 'noticia',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_video', models.CharField(max_length=50, verbose_name='Titulo Video')),
                ('fecha_video', models.DateField()),
                ('url_video', models.TextField()),
                ('is_active_video', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
