# Generated by Django 4.2.4 on 2023-09-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_delete_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='fecha_banner',
            field=models.DateField(verbose_name='Fecha Foto'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='foto_banner',
            field=models.ImageField(upload_to='banners', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active_video',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado banner'),
        ),
        migrations.AlterField(
            model_name='cumpleagno',
            name='fecha_cumple',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cumpleagno',
            name='foto_cumple',
            field=models.ImageField(upload_to='cumpleaños', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='cumpleagno',
            name='is_active_video',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado Cumpleaños'),
        ),
        migrations.AlterField(
            model_name='hito',
            name='fecha_hito',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='hito',
            name='is_active_hito',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado Hito'),
        ),
        migrations.AlterField(
            model_name='hito',
            name='lugar_hito',
            field=models.CharField(max_length=50, verbose_name='Lugar Hito'),
        ),
        migrations.AlterField(
            model_name='video',
            name='fecha_video',
            field=models.DateField(verbose_name='Fecha del Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_active_video',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_video',
            field=models.TextField(verbose_name='Url del Video'),
        ),
    ]
