# Generated by Django 4.2.4 on 2023-09-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_actividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='img_video',
            field=models.ImageField(null=True, upload_to='videos', verbose_name='Foto'),
        ),
    ]
