# Generated by Django 4.2.4 on 2023-09-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_delete_cumpleagno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_informativo', models.CharField(max_length=80, verbose_name='Informativo')),
                ('portada_informativo', models.ImageField(null=True, upload_to='actividades/portadas', verbose_name='Portada')),
                ('fecha_informativo', models.DateField(null=True, verbose_name='Fecha informativo')),
                ('is_active_informativo', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado Informativo')),
            ],
            options={
                'db_table': 'informativo',
            },
        ),
    ]
