# Generated by Django 4.2.4 on 2023-09-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_declaraciones_mision_and_more'),
        ('contenido', '0009_informativo_area_informativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='informativo',
            name='nombre_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.personas', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='informativo',
            name='area_informativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.equipos', verbose_name='Área'),
        ),
    ]
