# Generated by Django 4.2.4 on 2023-09-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0010_informativo_nombre_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informativo',
            name='portada_informativo',
            field=models.ImageField(null=True, upload_to='informativos', verbose_name='Portada'),
        ),
    ]
