# Generated by Django 4.2.4 on 2023-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0011_alter_informativo_portada_informativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividade',
            name='resegna_actividad',
            field=models.TextField(default='Reseña de la actividad', verbose_name='Reseña de la Actividad'),
            preserve_default=False,
        ),
    ]
