# Generated by Django 4.2.4 on 2023-09-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0012_actividade_resegna_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicadore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_kpis', models.CharField(max_length=100, verbose_name='Titulo Kpi')),
                ('fecha_kpis', models.DateField(verbose_name='Fecha Reporte')),
                ('url_kpis', models.TextField(verbose_name='Url del Reporte')),
                ('is_active_kpis', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado Reporte')),
            ],
            options={
                'db_table': 'indicadores',
            },
        ),
    ]
