# Generated by Django 4.2.4 on 2023-09-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0014_actividade_categoria_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='resegna_banner',
            field=models.TextField(default='hOLA', verbose_name='Reseña del Banner'),
            preserve_default=False,
        ),
    ]
