# Generated by Django 4.2.4 on 2023-09-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0015_banner_resegna_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hito',
            name='img_hito',
            field=models.ImageField(null=True, upload_to='hitos', verbose_name='Foto'),
        ),
    ]
