# Generated by Django 4.2.4 on 2023-09-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0016_hito_img_hito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_actividade',
            name='titulo_imagen',
            field=models.TextField(verbose_name='Titulo Imagen'),
        ),
    ]
