# Generated by Django 4.2.4 on 2023-09-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0017_alter_img_actividade_titulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividade',
            name='mostrar_inicio',
            field=models.CharField(choices=[('Mostrar', 'Mostrar'), ('Ocultar', 'Ocultar')], default='Ocultar', max_length=10, verbose_name='Mostrar en Inicio'),
        ),
    ]
