# Generated by Django 4.2.4 on 2023-09-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0018_actividade_mostrar_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='actividad_banner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenido.actividade', verbose_name='Actividad Asociada'),
            preserve_default=False,
        ),
    ]
