# Generated by Django 4.2.4 on 2023-09-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0019_banner_actividad_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30, verbose_name='Autor')),
                ('texto', models.TextField(verbose_name='Cometario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='contenido.actividade')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30, verbose_name='Autor')),
                ('texto', models.TextField(verbose_name='Respuesta')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='contenido.comentario')),
            ],
        ),
    ]
