# Generated by Django 4.2.4 on 2023-09-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='fotografia_equipo',
            field=models.ImageField(upload_to='equipos'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='fotografia_persona',
            field=models.ImageField(upload_to='personas'),
        ),
    ]
