# Generated by Django 4.2.4 on 2023-09-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_equipos_fotografia_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaraciones',
            name='mision',
            field=models.TextField(verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='declaraciones',
            name='proposito',
            field=models.TextField(verbose_name='Propósito'),
        ),
        migrations.AlterField(
            model_name='declaraciones',
            name='valores',
            field=models.TextField(verbose_name='Valores'),
        ),
        migrations.AlterField(
            model_name='declaraciones',
            name='vision',
            field=models.TextField(verbose_name='Visión'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción Equipo'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='fotografia_equipo',
            field=models.ImageField(upload_to='equipos', verbose_name='Foto Equipo'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Equipo'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.equipos', verbose_name='Equipo Asociado'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='fotografia_persona',
            field=models.ImageField(upload_to='personas', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='resegna',
            field=models.TextField(verbose_name='Reseña'),
        ),
    ]
