# Generated by Django 4.2.4 on 2023-09-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_declaraciones_mision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='correo',
            field=models.EmailField(default='correo@cdelmar.cl', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personas',
            name='telefono',
            field=models.CharField(default='+56912345678', max_length=12, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
