# Generated by Django 4.2.4 on 2023-09-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='cargo_per',
            field=models.TextField(default='Esta es la Frase', verbose_name='Cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipos',
            name='frase',
            field=models.TextField(default='Luis Pizarro', verbose_name='Frase del Equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipos',
            name='per_frase',
            field=models.TextField(default='Este es el cargo', verbose_name='Persona'),
            preserve_default=False,
        ),
    ]
