# Generated by Django 4.2.4 on 2023-09-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sustentabilidad', '0002_remove_img_practica_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_practica',
            name='fecha_imagen',
            field=models.DateField(verbose_name='Fecha Imagen'),
        ),
        migrations.AlterField(
            model_name='img_practica',
            name='img_practica',
            field=models.ImageField(upload_to='sustentabilidad', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='img_practica',
            name='is_active_img',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Esatdo Imagen'),
        ),
        migrations.AlterField(
            model_name='img_practica',
            name='practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustentabilidad.practica', verbose_name='Practica Asociada'),
        ),
        migrations.AlterField(
            model_name='practica',
            name='is_active_centro_costo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado Practica'),
        ),
    ]
