# Generated by Django 4.2.4 on 2023-09-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustentabilidad', '0003_alter_img_practica_fecha_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='descripcion',
            field=models.TextField(default='aaaaa'),
            preserve_default=False,
        ),
    ]
