# Generated by Django 4.2.4 on 2023-09-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_Noticia', models.CharField(max_length=50, verbose_name='Titulo Noticia')),
                ('fecha_noticia', models.DateField()),
                ('img_noticia', models.ImageField(upload_to='noticias')),
                ('url_noticia', models.TextField()),
                ('is_active_noticia', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'db_table': 'noticia',
            },
        ),
    ]
