# Generated by Django 4.2.4 on 2023-09-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_noticia',
            field=models.DateField(verbose_name='Fecha Noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img_noticia',
            field=models.ImageField(upload_to='noticias', verbose_name='Imagen Noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='is_active_noticia',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado Noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url_noticia',
            field=models.TextField(verbose_name='Url de la Noticia'),
        ),
    ]
