# Generated by Django 4.2.4 on 2023-09-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_planificacion', models.CharField(max_length=100, verbose_name='Titulo Noticia')),
                ('fecha_planificacion', models.DateField(verbose_name='Fecha Planificación')),
                ('url_planificacion', models.TextField(verbose_name='Url de la Planificación')),
                ('is_active_planificacion', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado Planificación')),
            ],
            options={
                'db_table': 'planificacion',
            },
        ),
    ]
