# Generated by Django 4.2.4 on 2023-09-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_reporte', models.CharField(max_length=100, verbose_name='Titulo Reporte')),
                ('fecha_reporte', models.DateField(verbose_name='Fecha Reporte')),
                ('url_reporte', models.TextField(verbose_name='Url de la Reporte')),
                ('is_active_reporte', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado Reporte')),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
    ]
